// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart.proto

package ds.project.heart;

public final class HeartServiceImpl {
  private HeartServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heart_heartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heart_heartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heart_heartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heart_heartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heart_slowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heart_slowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heart_slowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heart_slowResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013heart.proto\022\005heart\"!\n\014heartRequest\022\021\n\t" +
      "heartRate\030\001 \001(\005\"\"\n\rheartResponse\022\021\n\thear" +
      "tRate\030\001 \001(\005\"\036\n\013slowRequest\022\017\n\007tooHigh\030\001 " +
      "\001(\010\"\037\n\014slowResponse\022\017\n\007tooHigh\030\001 \001(\0102{\n\014" +
      "HeartService\0228\n\005Heart\022\023.heart.heartReque" +
      "st\032\024.heart.heartResponse\"\000(\0010\001\0221\n\004Slow\022\022" +
      ".heart.slowRequest\032\023.heart.slowResponse\"" +
      "\000B&\n\020ds.project.heartB\020HeartServiceImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_heart_heartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_heart_heartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heart_heartRequest_descriptor,
        new java.lang.String[] { "HeartRate", });
    internal_static_heart_heartResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_heart_heartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heart_heartResponse_descriptor,
        new java.lang.String[] { "HeartRate", });
    internal_static_heart_slowRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_heart_slowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heart_slowRequest_descriptor,
        new java.lang.String[] { "TooHigh", });
    internal_static_heart_slowResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_heart_slowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heart_slowResponse_descriptor,
        new java.lang.String[] { "TooHigh", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
