// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart.proto

package ds.project.heart;

public interface heartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heart.heartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 heartRate = 1;</code>
   */
  int getHeartRate();
}
