// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart.proto

package ds.project.heart;

public interface slowRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heart.slowRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool tooHigh = 1;</code>
   */
  boolean getTooHigh();
}
