// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speed.proto

package ds.project.speed;

public interface howLongLeftResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speed.howLongLeftResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 timeLeft = 1;</code>
   */
  int getTimeLeft();
}
