// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speed.proto

package ds.project.speed;

public interface howLongLeftRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speed.howLongLeftRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 distanceLeft = 1;</code>
   */
  int getDistanceLeft();
}
