// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speed.proto

package ds.project.speed;

public final class SpeedServiceImpl {
  private SpeedServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speed_speedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speed_speedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speed_speedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speed_speedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speed_howLongLeftRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speed_howLongLeftRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speed_howLongLeftResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speed_howLongLeftResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013speed.proto\022\005speed\"%\n\014speedRequest\022\025\n\r" +
      "current_speed\030\001 \001(\005\"&\n\rspeedResponse\022\025\n\r" +
      "current_speed\030\001 \001(\005\"*\n\022howLongLeftReques" +
      "t\022\024\n\014distanceLeft\030\001 \001(\005\"\'\n\023howLongLeftRe" +
      "sponse\022\020\n\010timeLeft\030\001 \001(\0052\220\001\n\014SpeedServic" +
      "e\0228\n\005Speed\022\023.speed.speedRequest\032\024.speed." +
      "speedResponse\"\000(\0010\001\022F\n\013howLongLeft\022\031.spe" +
      "ed.howLongLeftRequest\032\032.speed.howLongLef" +
      "tResponse\"\000B&\n\020ds.project.speedB\020SpeedSe" +
      "rviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_speed_speedRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_speed_speedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speed_speedRequest_descriptor,
        new java.lang.String[] { "CurrentSpeed", });
    internal_static_speed_speedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_speed_speedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speed_speedResponse_descriptor,
        new java.lang.String[] { "CurrentSpeed", });
    internal_static_speed_howLongLeftRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_speed_howLongLeftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speed_howLongLeftRequest_descriptor,
        new java.lang.String[] { "DistanceLeft", });
    internal_static_speed_howLongLeftResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_speed_howLongLeftResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speed_howLongLeftResponse_descriptor,
        new java.lang.String[] { "TimeLeft", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
