// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speed.proto

package ds.project.speed;

public interface speedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speed.speedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 current_speed = 1;</code>
   */
  int getCurrentSpeed();
}
