// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps.proto

package ds.project.gps;

public final class GpsServiceImpl {
  private GpsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gps_gpsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gps_gpsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gps_gpsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gps_gpsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gps_tdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gps_tdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gps_tdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gps_tdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tgps.proto\022\003gps\">\n\ngpsRequest\022\016\n\006x_axis" +
      "\030\001 \001(\005\022\016\n\006y_axis\030\002 \001(\005\022\020\n\010distance\030\003 \001(\005" +
      "\"-\n\013gpsResponse\022\016\n\006x_axis\030\001 \001(\005\022\016\n\006y_axi" +
      "s\030\002 \001(\005\"+\n\ttdRequest\022\016\n\006x_axis\030\001 \001(\005\022\016\n\006" +
      "y_axis\030\002 \001(\005\"0\n\ntdResponse\022\024\n\014distanceLe" +
      "ft\030\001 \001(\005\022\014\n\004time\030\002 \001(\0052p\n\nGpsService\022.\n\003" +
      "gps\022\017.gps.gpsRequest\032\020.gps.gpsResponse\"\000" +
      "(\0010\001\0222\n\rtime_distance\022\016.gps.tdRequest\032\017." +
      "gps.tdResponse\"\000B\"\n\016ds.project.gpsB\016GpsS" +
      "erviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gps_gpsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gps_gpsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gps_gpsRequest_descriptor,
        new java.lang.String[] { "XAxis", "YAxis", "Distance", });
    internal_static_gps_gpsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gps_gpsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gps_gpsResponse_descriptor,
        new java.lang.String[] { "XAxis", "YAxis", });
    internal_static_gps_tdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gps_tdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gps_tdRequest_descriptor,
        new java.lang.String[] { "XAxis", "YAxis", });
    internal_static_gps_tdResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gps_tdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gps_tdResponse_descriptor,
        new java.lang.String[] { "DistanceLeft", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
