// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps.proto

package ds.project.gps;

public interface tdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gps.tdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 distanceLeft = 1;</code>
   */
  int getDistanceLeft();

  /**
   * <code>int32 time = 2;</code>
   */
  int getTime();
}
