// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps.proto

package ds.project.gps;

public interface tdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gps.tdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x_axis = 1;</code>
   */
  int getXAxis();

  /**
   * <code>int32 y_axis = 2;</code>
   */
  int getYAxis();
}
